language: php
php:
        - 7.1
        - 7.2
        - 7.3

script:
        - composer install
        - vendor/bin/phpstan analyse -l max -c phpstan.neon --no-interaction --no-progress MultiSearch
